# Generated by Django 4.1.3 on 2022-11-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default='', max_length=200, verbose_name='password2'),
        ),
    ]
