# Generated by Django 4.1.2 on 2022-11-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='studio_images')),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('geographical_location', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('images', models.ManyToManyField(to='studio.image')),
            ],
        ),
    ]
