# Generated by Django 4.1.2 on 2022-11-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_location_alter_studio_geographical_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='geographical_location',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
