# Generated by Django 4.1.3 on 2022-11-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_amenities_delete_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='image',
            field=models.FileField(default='apple', upload_to='studio_images/'),
            preserve_default=False,
        ),
    ]
