# Generated by Django 4.1.3 on 2022-11-13 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_amenities_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenities',
            name='image',
        ),
    ]
