# Generated by Django 4.1.3 on 2022-11-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('coach', models.CharField(max_length=200)),
                ('keywords', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('times', models.TimeField()),
            ],
        ),
    ]
