# Generated by Django 4.1.3 on 2022-11-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('coach', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('date', models.DateField()),
                ('day', models.CharField(default='Monday', max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('studio', models.CharField(max_length=150)),
                ('keywords', models.ManyToManyField(to='classes.keyword')),
            ],
        ),
    ]
