# Generated by Django 4.1.3 on 2022-11-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='day',
            field=models.CharField(max_length=100),
        ),
    ]
