# Generated by Django 4.1.3 on 2022-11-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_classes_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='classes',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
