# Generated by Django 4.1.3 on 2022-11-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='class_instances',
            field=models.ManyToManyField(default=None, to='classes.class'),
        ),
    ]
