# Generated by Django 4.1.3 on 2022-11-16 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_classes_class_instances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='class_instances',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='day',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='start_time',
        ),
    ]
