# Generated by Django 4.1.3 on 2022-11-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_remove_classes_class_instances_remove_classes_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='studio',
            field=models.CharField(default='studio', max_length=150),
        ),
        migrations.AddField(
            model_name='classes',
            name='class_instances',
            field=models.ManyToManyField(default=None, to='classes.class'),
        ),
    ]
